name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_LINK: https://github.com/mozilla/sccache/releases/download
  SCCACHE_VERSION: v0.3.0
  SHELL: /bin/bash

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        rust: [stable, beta]
        include:
          - os: windows-latest
            id: windows
            sccache-path: C:\Users\runneradmin\Mozilla\sccache
          - os: macos-latest
            id: macos
            sccache-path: /Users/runner/Library/Caches/Mozilla.sccache
          - os: ubuntu-latest
            id: linux
            sccache-path: /home/runner/.cache/sccache
    env:
      CCACHE: sccache
      SCCACHE_CACHE_SIZE: 3G
      SCCACHE_DIR: ${{ matrix.sccache-path }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies on Windows
        if: matrix.id == 'windows'
        env:
          MOZILLA_BUILD_LINK: https://ftp.mozilla.org/pub/mozilla/libraries/win32
          MOZILLA_BUILD_VERSION: 3.4
          LLVM_VERSION: 14.0.6
        run: |
          Start-BitsTransfer -Source $env:MOZILLA_BUILD_LINK/MozillaBuildSetup-$env:MOZILLA_BUILD_VERSION.exe -Destination ./MozillaBuildSetup.exe
          .\MozillaBuildSetup.exe /S | Out-Null
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop install llvm@$env:LLVM_VERSION --global
          scoop install sccache --global
          echo "C:\ProgramData\scoop\shims;C:\Users\runneradmin\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Dependencies on OS X
        if: matrix.id == 'macos'
        run: |
          brew install python autoconf@2.13 llvm sccache yasm
      ## TODO: Remove when Homebrew Python 3.10 is supported
      ## TODO: Waiting on https://github.com/servo/rust-mozjs/issues/559
      - name: Install Python 3.9
        if: matrix.id == 'macos'
        run: |
          brew install python@3.9
          cd $(dirname $(which python3.9))
          rm -f python3 pip3
          ln -s python3.9 python3
          ln -s pip3.9 pip3

      - name: Install Dependencies on Linux
        if: matrix.id == 'linux'
        run: |
          sudo apt install autoconf2.13 clang llvm -y
          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
          mkdir -p $HOME/.local/bin
          curl -L "$SCCACHE_LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          chmod +x $SCCACHE_FILE/sccache
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          default: true
      - name: Install Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Cargo Cache and Git Database
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ matrix.id }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ matrix.id }}-
      - name: Cache sccache Cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.sccache-path }}
          key: sccache-${{ matrix.id }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            sccache-${{ matrix.id }}-

      - name: Start sccache Server
        run: sccache --start-server

      - name: Build POSIX
        if: matrix.id == 'macos' || matrix.id == 'linux'
        env:
          CC: clang
          CXX: clang++
          RUSTC_WRAPPER: sccache
        run: |
          just build-release -vvv
          just test-release -vvv
          mv ./target/release/cli ./target/release/spiderfire
          strip ./target/release/spiderfire

      - name: Build Windows
        if: matrix.id == 'windows' && matrix.rust != 'beta'
        shell: cmd
        env:
          CARGO_HOME: ${{ github.workspace }}\..\.cargo
          MOZTOOLS_PATH: C:\mozilla-build\msys\bin;C:\mozilla-build\bin
          AUTOCONF: C:\mozilla-build\msys\local\bin\autoconf-2.13
          CC: clang-cl.exe
          CXX: clang-cl.exe
          LINKER: lld-link.exe
          NATIVE_WIN32_PYTHON: C:\mozilla-build\python\python.exe
          PYTHON3: C:\mozilla-build\python3\python3.exe
          LIBCLANG_PATH: C:\ProgramData\scoop\apps\llvm\current\lib
        run: |
          just build-release -vvv
          just test-release -vvv
          rename .\target\release\cli.exe spiderfire.exe

      - name: Stop sccache Server
        run: |
          sccache --show-stats
          sccache --stop-server || true

      - name: Upload Executables as Artifacts
        uses: actions/upload-artifact@v2
        if: matrix.rust == 'stable'
        with:
          name: spiderfire-${{ github.sha }}-${{ matrix.id }}
          path: target/release/spiderfire${{ matrix.id == 'windows' && '.exe' || '' }}
          if-no-files-found: error

  Lint:
    runs-on: ubuntu-latest
    env:
      CCACHE: sccache
      SCCACHE_CACHE_SIZE: 1G
      SCCACHE_DIR: /home/runner/.cache/sccache

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies on Linux
        run: |
          sudo apt install autoconf2.13 clang llvm -y
          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
          mkdir -p $HOME/.local/bin
          curl -L "$SCCACHE_LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          chmod +x $SCCACHE_FILE/sccache
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          default: true
      - name: Install Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Cargo Cache and Git Database
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-lint-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-lint-
      - name: Cache sccache Cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/sccache
          key: sccache-lint-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            sccache-lint-

      - name: Start sccache Server
        run: sccache --start-server

      - name: Lint
        env:
          CC: clang
          CXX: clang++
          RUSTC_WRAPPER: sccache
        run: |
          just lint

      - name: Stop sccache Server
        run: |
          sccache --show-stats
          sccache --stop-server || true
